apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Mindforce-cluster
  region: us-east-1
  version: "1.29"

managedNodeGroups:
  - name: ng-general
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    privateNetworking: true
    amiFamily: AmazonLinux2
