apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: Mindforce-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Mindforce-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
